### ISSUE TITLE
Mention dependencies

### ISSUE THREAD

**Issue by roshniRam** [sugarlabs/sugar-artwork#108]
Some of the people might not know what the dependencies are, so, instead of install all dependencies, the dependencies should be mentioned.

**Comment by quozl** [comment]
No thanks, we don’t track them.  Because downstream distributions can change which of our dependencies are packaged by default and which are not.  For advice specific to Fedora or Debian, see the how to set up a development environment in sugar-docs.  For other distributions, contact them.
